{ pkgs, devClosure, ... }:

{
  home.packages =
    let
      topLevel = with pkgs; [
        gst_all_1.gstreamer
        gst_all_1.gst-plugins-base
        gst_all_1.gst-plugins-good
        gst_all_1.gst-plugins-bad
        gst_all_1.gst-plugins-ugly
        gst_all_1.gst-plugins-rs
        gst_all_1.gst-libav
        lua
        luarocks
        sqlfluff
        typstyle
        vivify
        glab
        croc
        binaryen
        bat-extras.batpipe
        bat-extras.batman
        bat-extras.batgrep
        nodejs_latest
        pinact
        zig
        tmux
        superfile
        protobuf
        opencode
        mold
        btop
        yq
        github-cli
        glow
        go
        pandoc
        lazygit
        fastfetch
        lazydocker
        direnv
        satty
        slurp
        gpu-screen-recorder
        azure-cli
        aflplusplus
        # Kani CBMC solvers
        cadical
        minisat
        kissat
        z3
        bitwuzla
        cvc5
        perf
        libllvm
        yt-dlp
        entr
        rustdesk
        sqlite
        texliveBasic
        biber
        tectonic
        statix
        ghostscript
        libnotify
        ghostty
        imagemagick
        fzf
        vivid
        clang
        nwg-look
        cava
        pavucontrol
        cmake
        gnumake
        git-credential-keepassxc
        vicinae
        matugen
        khal
        vdirsyncer
        wtype
        dgop
        libsForQt5.qt5ct
        qt6Packages.qt6ct
        nautilus
        nautilus-open-any-terminal
        evince
        loupe
        networkmanagerapplet
        adw-gtk3
        ddcutil
        (discord.override {
          withVencord = true;
        })
        cachix
        nh
        kdePackages.kdeconnect-kde
        udisks
        amberol
        celluloid
        gnome-calculator
        thunderbird
        emacs
        eask-cli
        doppler
        gvfs
        simple-mtpfs
        libmtp
        gnome-online-accounts-gtk
        keepassxc
        rclone-browser
        rclone
        nixfmt
      ];
    in
    topLevel ++ devClosure topLevel;
}
