-- DMS user keybind overrides (edit via Control Center or dms; do not remove this header)

hl.unbind("ALT + Print")
hl.bind("ALT + Print", hl.dsp.exec_cmd("dms ipc call screenCaptureToolbar toggle"), { description = "dms screenshot window" })
hl.unbind("CTRL + Print")
hl.bind("CTRL + Print", hl.dsp.exec_cmd("dms ipc call screenCaptureToolbar toggle"), { description = "dms screenshot full" })
hl.unbind("Print")
hl.bind("Print", hl.dsp.exec_cmd("dms ipc call screenCaptureToolbar toggle"), { description = "dms screenshot" })
hl.unbind("SUPER + Return")
hl.bind("SUPER + Return", hl.dsp.exec_cmd("ghostty +new-window"))
hl.unbind("SUPER + D")
hl.bind("SUPER + D", hl.dsp.exec_cmd("vicinae toggle"))
hl.unbind("SUPER + V")
hl.bind("SUPER + V", hl.dsp.exec_cmd("vicinae vicinae://launch/clipboard/history"))
