[tools]
node = "latest"
deno = "latest"
python = "latest"
yarn = "latest"
shellcheck = "latest"
gitleaks = "latest"
gh = "latest"
direnv = "latest"
pnpm = "latest"
zig = "latest"
uv = "latest"
bat = "latest"
bat-extras = "latest"
btop = "latest"
dust = "latest"
delta = "latest"
lazydocker = "latest"
usage = "latest"
fastfetch = "latest"
eza = "latest"
fd = "latest"
glow = "latest"
lazygit = "latest"
"pipx:sherlock-project" = "latest"
tlrc = "latest"
atuin = "latest"
superfile = "latest"
"ubi:sundowndev/phoneinfoga" = "latest"
neonctl = "latest"
"npm:wordnet" = "latest"
lychee = "latest"
neovim = "latest"
"ubi:neovide/neovide" = "latest"
claude-code = "latest"
opencode = "latest"
pandoc = "latest"
ollama = "latest"
"pipx:ty" = "latest"
"pipx:posting" = "latest"
"cargo:pay-respects" = "latest"
rust-analyzer = "latest"
starship = "latest"
yay = "latest"
yazi = "latest"
yq = "latest"
zoxide = "latest"
"pipx:zizmor" = "latest"
hyperfine = "latest"
"cargo:speedtest-rs" = "latest"
"cargo:wallust" = "latest"
"cargo:flamegraph" = "latest"
"cargo:tauri-cli" = "latest"
"cargo:cargo-deny" = "latest"
"cargo:cargo-audit" = "latest"
"cargo:typos-cli" = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:kanata" = "latest"
"cargo:iai-callgrind-runner" = "latest"
"cargo:git-cliff" = "latest"
"cargo:cargo-zigbuild" = "latest"
"cargo:cargo-tarpaulin" = "latest"
"cargo:cargo-shear" = "latest"
"npm:@charmland/crush" = "latest"
"npm:copilot-api" = "latest"
hk = "latest"
pkl = "latest"
java = "latest"
"cargo:cargo-edit" = "latest"
"cargo:cargo-update" = "latest"
"cargo:cargo-features-manager" = "latest"
sccache = "latest"
"cargo:rustowl" = "latest"
"npm:@openai/codex" = "latest"
"cargo:cargo-llvm-cov" = "latest"
"pipx:mcp-proxy" = "latest"
"pipx:vectorcode" = { version = "latest", extras = "lsp,mcp,intel" }
bun = "1.2.23"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:neovim" = "latest"
stylua = "latest"
shfmt = "latest"
biome = "latest"
hadolint = "latest"
markdownlint-cli2 = "latest"
yamllint = "latest"
github-markdown-toc = "latest"
"pipx:mdformat" = { version = "latest", uvx_args = "--with=mdformat-gfm,mdformat-frontmatter,mdformat-footnote,mdformat-gfm-alerts" }
yamlfmt = "latest"
"npm:@fsouza/prettierd" = "latest"
"pipx:shandy-sqlfmt" = "latest"
"http:vscode-js-debug" = { version = "1.104.0", url = "https://github.com/microsoft/vscode-js-debug/releases/download/v1.104.0/js-debug-dap-v1.104.0.tar.gz" }
codelldb = "latest"
ast-grep = "latest"
harper-ls = "latest"
"npm:@vue/language-server" = "latest"
zls = "latest"
"pipx:tombi" = "latest"
"npm:oxlint" = "latest"
"npm:vim-language-server" = "latest"
"npm:@mdx-js/language-server" = "latest"
"npm:yaml-language-server" = "latest"
"npm:tailwindcss-language-server" = "latest"
"pipx:ruff" = "latest"
"npm:@prisma/language-server" = "latest"
lua-language-server = "latest"
go = "latest"
"github:hyprland-community/hyprls" = "latest"
"npm:@olrtg/emmet-language-server" = "latest"
"npm:dot-language-server" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:@microsoft/compose-language-service" = "latest"
"npm:cssmodules-language-server" = "latest"
"npm:css-variables-language-server" = "latest"
"npm:bash-language-server" = "latest"
"npm:@astrojs/language-server" = "latest"
"github:tekumara/typos-lsp" = "latest"
"github:artempyanykh/marksman" = "latest"
"github:Feel-ix-343/markdown-oxide" = "latest"
"github:terror/just-lsp" = "latest"
"github:errata-ai/vale-ls" = "latest"
"npm:@vtsls/language-server" = "latest"
"aqua:cargo-binstall" = "latest"
"npm:@t1ckbase/vscode-langservers-extracted" = "latest"
"aqua:Kampfkarren/selene" = "latest"

[settings]
lockfile = true
experimental = true
idiomatic_version_file_enable_tools = ["rust"]

[settings.python]
compile = false

[settings.npm]
bun = true

[settings.pipx]
uvx = true

[settings.cargo]
binstall = true
