[tools]
"aqua:nodejs/node" = "latest"
gh = "latest"
direnv = "latest"
pnpm = "latest"
uv = "latest"
bat = "latest"
dust = "latest"
delta = "latest"
lazydocker = "latest"
usage = "latest"
fastfetch = "latest"
eza = "latest"
fd = "latest"
lazygit = "latest"
atuin = "latest"
pandoc = "latest"
"pipx:ty" = "latest"
"pipx:posting" = "latest"
"cargo-binstall" = "latest"
"cargo:pay-respects" = "latest"
rust-analyzer = "latest"
starship = "latest"
zoxide = "latest"
"pipx:zizmor" = "latest"
hyperfine = "latest"
"cargo:speedtest-rs" = "latest"
"cargo:flamegraph" = "latest"
"cargo:cargo-deny" = "latest"
"cargo:cargo-audit" = "latest"
"cargo:typos-cli" = "latest"
"cargo:tokei" = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:kanata" = "latest"
"cargo:iai-callgrind-runner" = "latest"
"cargo:cargo-zigbuild" = "latest"
"cargo:cargo-shear" = "latest"
"cargo:cargo-update" = "latest"
sccache = "latest"
"cargo:cargo-llvm-cov" = "latest"
bun = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"pipx:tombi" = "latest"
"pipx:ruff" = "latest"
go = "latest"
"cargo:just" = "latest"
"cargo:cargo-insta" = "latest"
pinact = "latest"
"cargo:cargo-subspace" = "latest"
"cargo:cargo-udeps" = "latest"
"cargo:cargo-dist" = "latest"
"cargo:cargo-release" = "latest"
"go:github.com/schollz/croc/v10" = "latest"
"cargo:tealdeer" = "latest"
zellij = "latest"
"cargo:rusty-man" = "latest"
"cargo:nu" = "latest"
"cargo:wasm-pack" = "latest"
wasmtime = "latest"
"gitlab:gitlab-org/cli" = "latest"
"github:eth-p/bat-extras" = "latest"
"github:WebAssembly/binaryen" = "latest"
"cargo:cargo-edit" = "latest"
"cargo:cargo-fuzz" = "latest"
"npm:copilot-api" = "latest"
"github:jannis-baum/Vivify" = "latest"
glow = "latest"
"cargo:cargo-hack" = "latest"
github-cli = "latest"
"cargo:cargo-features-manager" = "latest"
"cargo:rmpc" = "latest"
yq = "latest"
"npm:@github/copilot" = "latest"
ripgrep = "latest"
btop = "latest"
python = "latest"
mold = "latest"
jq = "latest"
git-cliff = "latest"
opencode = "latest"
"github:can1357/oh-my-pi" = "latest"
protoc = "latest"
superfile = "latest"

[settings]
lockfile = true
experimental = true
idiomatic_version_file_enable_tools = ["rust"]

[settings.python]
compile = false

[settings.pipx]
uvx = true

[settings.cargo]
binstall = true
