# Fish abbreviations — converted from zsh-abbr
# Generated 338 abbreviations, skipped 8
# Source: ~/.config/zsh-abbr/user-abbreviations

# Note: 'noglob' entries converted to plain commands.
# Fish has no noglob builtin; quote glob characters manually.

# FIXME (zsh-specific constructs that need manual attention):
#   gk/gke — &! is zsh background+disown; use &; disown
#   gtl   — defines a bash function inline; not portable to fish
#   npmE  — bash-style PATH=value; use 'set -gx PATH (npm bin) $PATH' instead

# Git helper functions used by abbreviations
function git_current_branch
    git branch --show-current 2>/dev/null
end
function git_develop_branch
    echo develop
end
function git_main_branch
    set -l branch (git remote show origin 2>/dev/null | string match -r "HEAD branch: (.+)" | head -1)
    if test -z "$branch"
        echo main
    else
        echo $branch[1]
    end
end

abbr --add ... '../..'
abbr --add .... '../../..'
abbr --add ..... '../../../..'
abbr --add ...... '../../../../..'
abbr --add --position anywhere -- -h '-h 2>&1 | bat --language=help --style=plain'
abbr --add --position anywhere -- --help '--help 2>&1 | bat --language=help --style=plain'
abbr --add -- - 'cd -'
abbr --add _ 'sudo '
abbr --add 1 'cd -1'
abbr --add 2 'cd -2'
abbr --add 3 'cd -3'
abbr --add 4 'cd -4'
abbr --add 5 'cd -5'
abbr --add 6 'cd -6'
abbr --add 7 'cd -7'
abbr --add 8 'cd -8'
abbr --add 9 'cd -9'
abbr --add cat 'bat --paging=never'
abbr --add clock 'tty-clock -tcBrsSC 6'
abbr --add db 'deno bundle'
abbr --add dc 'deno compile'
abbr --add dca 'deno cache'
abbr --add dfmt 'deno fmt'
abbr --add dh 'deno help'
abbr --add dli 'deno lint'
abbr --add drA 'deno run -A'
abbr --add drn 'deno run'
abbr --add dru 'deno run --unstable'
abbr --add drw 'deno run --watch'
abbr --add dts 'deno test'
abbr --add dup 'deno upgrade'
abbr --add egrep 'grep -E'
abbr --add fgrep 'grep -F'
abbr --add fsh-alias fast-theme
abbr --add g git
abbr --add ga 'git add'
abbr --add gaa 'git add --all'
abbr --add gam 'git am'
abbr --add gama 'git am --abort'
abbr --add gamc 'git am --continue'
abbr --add gams 'git am --skip'
abbr --add gamscp 'git am --show-current-patch'
abbr --add gap 'git apply'
abbr --add gapa 'git add --patch'
abbr --add gapt 'git apply --3way'
abbr --add gau 'git add --update'
abbr --add gav 'git add --verbose'
abbr --add gb 'git branch'
abbr --add gba 'git branch --all'
abbr --add gbd 'git branch --delete'
abbr --add gbD 'git branch --delete --force'
abbr --add gbg 'LANG=C git branch -vv | grep ": gone]"'
abbr --add gbgd "LANG=C git branch --no-color -vv | grep \": gone]\" | cut -c 3- | awk '{print \$1}' | xargs git branch -d"
abbr --add gbgD "LANG=C git branch --no-color -vv | grep \": gone]\" | cut -c 3- | awk '{print \$1}' | xargs git branch -D"
abbr --add gbl 'git blame -w'
abbr --add gbm 'git branch --move'
abbr --add gbnm 'git branch --no-merged'
abbr --add gbr 'git branch --remote'
abbr --add gbs 'git bisect'
abbr --add gbsb 'git bisect bad'
abbr --add gbsg 'git bisect good'
abbr --add gbsn 'git bisect new'
abbr --add gbso 'git bisect old'
abbr --add gbsr 'git bisect reset'
abbr --add gbss 'git bisect start'
abbr --add gc 'git commit --verbose'
abbr --add gc\! 'git commit --verbose --amend'
abbr --add gca 'git commit --verbose --all'
abbr --add gca\! 'git commit --verbose --all --amend'
abbr --add gcam 'git commit --all --message'
abbr --add gcan\! 'git commit --verbose --all --no-edit --amend'
abbr --add gcann\! 'git commit --verbose --all --date=now --no-edit --amend'
abbr --add gcans\! 'git commit --verbose --all --signoff --no-edit --amend'
abbr --add gcas 'git commit --all --signoff'
abbr --add gcasm 'git commit --all --signoff --message'
abbr --add gcb 'git checkout -b'
abbr --add gcB 'git checkout -B'
abbr --add gcc 'gcc -fuse-ld=mold'
abbr --add gcd 'git checkout (git_develop_branch)'
abbr --add gcf 'git config --list'
abbr --add gcfu 'git commit --fixup'
abbr --add gcl 'git clone --recurse-submodules'
abbr --add gclean 'git clean --interactive -d'
abbr --add gclf 'git clone --recursive --shallow-submodules --filter=blob:none --also-filter-submodules'
abbr --add gcm 'git checkout (git_main_branch)'
abbr --add gcmsg 'git commit --message'
abbr --add gcn 'git commit --verbose --no-edit'
abbr --add gcn\! 'git commit --verbose --no-edit --amend'
abbr --add gco 'git checkout'
abbr --add gcor 'git checkout --recurse-submodules'
abbr --add gcount 'git shortlog --summary --numbered'
abbr --add gcp 'git cherry-pick'
abbr --add gcpa 'git cherry-pick --abort'
abbr --add gcpc 'git cherry-pick --continue'
abbr --add gcs 'git commit --gpg-sign'
abbr --add gcsm 'git commit --signoff --message'
abbr --add gcss 'git commit --gpg-sign --signoff'
abbr --add gcssm 'git commit --gpg-sign --signoff --message'
abbr --add gd 'git diff'
abbr --add gdca 'git diff --cached'
abbr --add gdct 'git describe --tags (git rev-list --tags --max-count=1)'
abbr --add gdcw 'git diff --cached --word-diff'
abbr --add gds 'git diff --staged'
abbr --add gdt 'git diff-tree --no-commit-id --name-only -r'
abbr --add gdup 'git diff @{upstream}'
abbr --add gdw 'git diff --word-diff'
abbr --add gf 'git fetch'
abbr --add gfa 'git fetch --all --tags --prune --jobs=10'
abbr --add gfg 'git ls-files | grep'
abbr --add gfo 'git fetch origin'
abbr --add gg 'git gui citool'
abbr --add gga 'git gui citool --amend'
abbr --add ggpull 'git pull origin "(git_current_branch)"'
# ggu = git pull upstream (git_current_branch)
abbr --add ggu 'git pull upstream (git_current_branch)'
abbr --add ggpur ggu
abbr --add ggpush 'git push origin "(git_current_branch)"'
abbr --add ggsup 'git branch --set-upstream-to=origin/(git_current_branch)'
abbr --add ghh 'git help'
abbr --add gignore 'git update-index --assume-unchanged'
abbr --add gignored 'git ls-files -v | grep "^[[:lower:]]"'
abbr --add git-svn-dcommit-push 'git svn dcommit && git push github (git_main_branch):svntrunk'
abbr --add gk 'gitk --all --branches &!'
abbr --add gke 'gitk --all (git log --walk-reflogs --pretty=%h) &!'
abbr --add gl 'git pull'
abbr --add glg 'git log --stat'
abbr --add glgg 'git log --graph'
abbr --add glgga 'git log --graph --decorate --all'
abbr --add glgm 'git log --graph --max-count=10'
abbr --add glgp 'git log --stat --patch'
abbr --add glo 'git log --oneline --decorate'
abbr --add globurl 'urlglobber '
abbr --add glod 'git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset"'
abbr --add glods 'git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset" --date=short'
abbr --add glog 'git log --oneline --decorate --graph'
abbr --add gloga 'git log --oneline --decorate --graph --all'
abbr --add glol 'git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset"'
abbr --add glola 'git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset" --all'
abbr --add glols 'git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset" --stat'
abbr --add gluc 'git pull upstream (git_current_branch)'
abbr --add glum 'git pull upstream (git_main_branch)'
abbr --add gm 'git merge'
abbr --add gma 'git merge --abort'
abbr --add gmc 'git merge --continue'
abbr --add gmff 'git merge --ff-only'
abbr --add gmom 'git merge origin/(git_main_branch)'
abbr --add gms 'git merge --squash'
abbr --add gmtl 'git mergetool --no-prompt'
abbr --add gmtlvim 'git mergetool --no-prompt --tool=vimdiff'
abbr --add gmum 'git merge upstream/(git_main_branch)'
abbr --add gp 'git push'
abbr --add gpd 'git push --dry-run'
abbr --add gpf 'git push --force-with-lease --force-if-includes'
abbr --add gpf\! 'git push --force'
abbr --add gpoat 'git push origin --all && git push origin --tags'
abbr --add gpod 'git push origin --delete'
abbr --add gpr 'git pull --rebase'
abbr --add gpra 'git pull --rebase --autostash'
abbr --add gprav 'git pull --rebase --autostash -v'
abbr --add gpristine 'git reset --hard && git clean --force -dfx'
abbr --add gprom 'git pull --rebase origin (git_main_branch)'
abbr --add gpromi 'git pull --rebase=interactive origin (git_main_branch)'
abbr --add gprum 'git pull --rebase upstream (git_main_branch)'
abbr --add gprumi 'git pull --rebase=interactive upstream (git_main_branch)'
abbr --add gprv 'git pull --rebase -v'
abbr --add gpsup 'git push --set-upstream origin (git_current_branch)'
abbr --add gpsupf 'git push --set-upstream origin (git_current_branch) --force-with-lease --force-if-includes'
abbr --add gpu 'git push upstream'
abbr --add gpv 'git push --verbose'
abbr --add gr 'git remote'
abbr --add gra 'git remote add'
abbr --add grb 'git rebase'
abbr --add grba 'git rebase --abort'
abbr --add grbc 'git rebase --continue'
abbr --add grbd 'git rebase (git_develop_branch)'
abbr --add grbi 'git rebase --interactive'
abbr --add grbm 'git rebase (git_main_branch)'
abbr --add grbo 'git rebase --onto'
abbr --add grbom 'git rebase origin/(git_main_branch)'
abbr --add grbs 'git rebase --skip'
abbr --add grbum 'git rebase upstream/(git_main_branch)'
abbr --add grep 'grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox,.venv,venv}'
abbr --add grev 'git revert'
abbr --add greva 'git revert --abort'
abbr --add grevc 'git revert --continue'
abbr --add grf 'git reflog'
abbr --add grh 'git reset'
abbr --add grhh 'git reset --hard'
abbr --add grhk 'git reset --keep'
abbr --add grhs 'git reset --soft'
abbr --add grm 'git rm'
abbr --add grmc 'git rm --cached'
abbr --add grmv 'git remote rename'
abbr --add groh 'git reset origin/(git_current_branch) --hard'
abbr --add grrm 'git remote remove'
abbr --add grs 'git restore'
abbr --add grset 'git remote set-url'
abbr --add grss 'git restore --source'
abbr --add grst 'git restore --staged'
abbr --add grt 'cd "(git rev-parse --show-toplevel || echo .)"'
abbr --add gru 'git reset --'
abbr --add grup 'git remote update'
abbr --add grv 'git remote --verbose'
abbr --add gsb 'git status --short --branch'
abbr --add gsd 'git svn dcommit'
abbr --add gsh 'git show'
abbr --add gsi 'git submodule init'
abbr --add gsps 'git show --pretty=short --show-signature'
abbr --add gsr 'git svn rebase'
abbr --add gss 'git status --short'
abbr --add gst 'git status'
abbr --add gsta 'git stash push'
abbr --add gstaa 'git stash apply'
abbr --add gstall 'git stash --all'
abbr --add gstc 'git stash clear'
abbr --add gstd 'git stash drop'
abbr --add gstl 'git stash list'
abbr --add gstp 'git stash pop'
abbr --add gsts 'git stash show --patch'
abbr --add gstu 'gsta --include-untracked'
abbr --add gsu 'git submodule update'
abbr --add gsw 'git switch'
abbr --add gswc 'git switch --create'
abbr --add gswd 'git switch (git_develop_branch)'
abbr --add gswm 'git switch (git_main_branch)'
abbr --add gta 'git tag --annotate'
abbr --add gtl 'gtl(){ git tag --sort=-v:refname -n --list "${1}*" }; gtl'
abbr --add gts 'git tag --sign'
abbr --add gtv 'git tag | sort -V'
abbr --add gunignore 'git update-index --no-assume-unchanged'
abbr --add gunwip 'git rev-list --max-count=1 --format="%s" HEAD | grep -q "--wip--" && git reset HEAD~1'
abbr --add gwch 'git log --patch --abbrev-commit --pretty=medium --raw'
abbr --add gwip 'git add -A; git rm (git ls-files --deleted) 2> /dev/null; git commit --no-verify --no-gpg-sign --message "--wip-- [skip ci]"'
abbr --add gwipe 'git reset --hard && git clean --force -df'
abbr --add gwt 'git worktree'
abbr --add gwta 'git worktree add'
abbr --add gwtls 'git worktree list'
abbr --add gwtmv 'git worktree move'
abbr --add gwtrm 'git worktree remove'
abbr --add l 'ls -lah'
abbr --add la 'eza -gla'
abbr --add lD 'eza -glD'
abbr --add lDD 'eza -glDa'
abbr --add ldot 'eza -gld .*'
abbr --add ll 'eza -gl'
abbr --add ls eza
abbr --add lS 'eza -gl -ssize'
abbr --add lsa 'ls -lah'
abbr --add lsd 'eza -gd'
abbr --add lsdl 'eza -gdl'
abbr --add lT 'eza -gl -snewest'
abbr --add ltree 'eza --tree --level=2  --icons --git --git-ignore'
abbr --add md 'mkdir -p'
abbr --add npmD 'npm i -D '
abbr --add npmE 'PATH="(npm bin)":"$PATH"'
abbr --add npmF 'npm i -f'
abbr --add npmg 'npm i -g '
abbr --add npmi 'npm info'
abbr --add npmI 'npm init'
abbr --add npmL 'npm list'
abbr --add npmL0 'npm ls --depth=0'
abbr --add npmO 'npm outdated'
abbr --add npmP 'npm publish'
abbr --add npmR 'npm run'
abbr --add npmrb 'npm run build'
abbr --add npmrd 'npm run dev'
abbr --add npmS 'npm i -S '
abbr --add npmSe 'npm search'
abbr --add npmst 'npm start'
abbr --add npmt 'npm test'
abbr --add npmU 'npm update'
abbr --add npmV 'npm -v'
abbr --add open xdg-open
abbr --add pacfiles 'pacman -F'
abbr --add pacfileupg 'sudo pacman -Fy'
abbr --add pacin 'sudo pacman -S'
abbr --add pacins 'sudo pacman -U'
abbr --add pacinsd 'sudo pacman -S --asdeps'
abbr --add paclean 'sudo pacman -Sc'
abbr --add pacloc 'pacman -Qi'
abbr --add paclocs 'pacman -Qs'
abbr --add paclr 'sudo pacman -Scc'
abbr --add pacls 'pacman -Ql'
abbr --add paclsorphans 'sudo pacman -Qdt'
abbr --add pacmanallkeys 'sudo pacman-key --refresh-keys'
abbr --add pacmir 'sudo pacman -Syy'
abbr --add pacown 'pacman -Qo'
abbr --add pacre 'sudo pacman -R'
abbr --add pacrem 'sudo pacman -Rns'
abbr --add pacrep 'pacman -Si'
abbr --add pacreps 'pacman -Ss'
abbr --add pacrmorphans 'sudo pacman -Rs (pacman -Qtdq)'
abbr --add pacupd 'sudo pacman -Sy'
abbr --add pacupg 'sudo pacman -Syu'
abbr --add pbcopy wl-copy
abbr --add pbpaste wl-paste
abbr --add pip pip
abbr --add pipgi 'pip freeze | grep'
abbr --add pipi 'pip install'
abbr --add pipir 'pip install -r requirements.txt'
abbr --add piplo 'pip list -o'
abbr --add pipreq 'pip freeze > requirements.txt'
abbr --add pipu 'pip install --upgrade'
abbr --add pipun 'pip uninstall'
abbr --add py python3
abbr --add pyfind 'find . -name "*.py"'
abbr --add pygrep 'grep -nr --include="*.py"'
abbr --add pyserver 'python3 -m http.server'
abbr --add rd rmdir
abbr --add uv uv
abbr --add uva 'uv add'
abbr --add uvexp 'uv export --format requirements-txt --no-hashes --output-file requirements.txt --quiet'
abbr --add uvi 'uv init'
abbr --add uvinw 'uv init --no-workspace'
abbr --add uvl 'uv lock'
abbr --add uvlr 'uv lock --refresh'
abbr --add uvlu 'uv lock --upgrade'
abbr --add uvp 'uv pip'
abbr --add uvpi 'uv python install'
abbr --add uvpl 'uv python list'
abbr --add uvpp 'uv python pin'
abbr --add uvpu 'uv python uninstall'
abbr --add uvpy 'uv python'
abbr --add uvr 'uv run'
abbr --add uvrm 'uv remove'
abbr --add uvs 'uv sync'
abbr --add uvsr 'uv sync --refresh'
abbr --add uvsu 'uv sync --upgrade'
abbr --add uvtr 'uv tree'
abbr --add uvup 'uv self update'
abbr --add uvv 'uv venv'
abbr --add zi zinit
abbr --add zini zinit
abbr --add zpl zinit
abbr --add zplg zinit
