"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os \
$username\
$directory\
$git_branch\
$git_status\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$docker_context\
$time\
$fill$cmd_duration\
$line_break$character"""

continuation_prompt = '[❯❯](bright-black)'

palette = 'catppuccin_mocha'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
orange = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = false

[os.symbols]
Windows = "[󰍲](fg:#0078d7)"
Ubuntu = "[󰕈](fg:#E95420)"
SUSE = "[](fg:#73ba25)"
Raspbian = "[󰐿](fg:#C51A4A)"
Mint = "[󰣭](fg:#86BE43)"
Macos = "[](fg:white)"
Manjaro = "[](fg:#34be5b)"
Linux = "[](fg:#000000)"
Gentoo = "[󰣨](fg:#54487A)"
Fedora = "[󰣛](fg:#0B57A4)"
Alpine = "[](fg:#005880)"
Amazon = "[](fg:#FF9900)"
Android = "[](fg:#3ddc84)"
Arch = "[󰣇](fg:#1793d1)"
Artix = "[](fg:cyan)"
CentOS = "[](fg:#9ECE26)"
Debian = "[󰣚](fg:#d70a53)"
Redhat = "[󱄛](fg:#ee0000)"
RedHatEnterprise = "[󱄛](fg:#ee0000)"

[username]
show_always = true
style_user = "fg:text"
style_root = "fg:text"
format = '[ $user ]($style)'

[directory]
style = "fg:peach"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "fg:teal"
format = '[[ $symbol $branch ](fg:green)]($style)'

[git_status]
style = "fg:teal"
format = '[[($all_status$ahead_behind )](fg:green)]($style)'

[nodejs]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:#3c873a)]($style)'

[c]
symbol = " "
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:#00599d)]($style)'

[rust]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:#f54b01)]($style)'

[golang]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:#75e0fd)]($style)'

[php]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:#777bb3)]($style)'

[java]
symbol = " "
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:#5283a3)]($style)'

[kotlin]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:#9f38f7)]($style)'

[haskell]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:#5e5086)]($style)'

[python]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:#ffdf59)]($style)'

[docker_context]
symbol = ""
style = "fg:mantle"
format = '[[ $symbol( $context) ](fg:#83a598)]($style)'

[time]
disabled = false
time_format = "%I:%M %p"
style = "fg:peach"
format = '[[  $time ](fg:purple)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:creen)'
vimcmd_replace_one_symbol = '[❮](bold fg:purple)'
vimcmd_replace_symbol = '[❮](bold fg:purple)'
vimcmd_visual_symbol = '[❮](bold fg:lavender)'

[cmd_duration]
min_time = 0
format = '  [  $duration](bold blue)'
disabled = false

[fill]
symbol = ' .'
style = 'fg:surface2'
disabled = false
