layerrules = true

[windows]
scale = 8.5
workspaces_per_row = 5
strip_html_from_workspace_title = true

[windows.switch.open]
modifier = "alt"

[windows.switch.navigate]
forward = "tab"

[windows.switch.navigate.reverse]
key = "grave"

[windows.switch.other]
filter_by = []
hide_filtered = true
