-- ! AUTO-GENERATED BY dmsThemeSync — DO NOT EDIT !
-- ! Cursor and Qt platform theme managed by the DMS Theme Sync plugin. !
hl.env("XCURSOR_THEME", "Windows")
hl.env("HYPRCURSOR_THEME", "Windows")
hl.env("XCURSOR_SIZE", "25")
hl.env("HYPRCURSOR_SIZE", "25")
