local M = {
	misc = {
		dots = "󰇘",
		color_text = "󱓻",
		env = " ",
		shelter_env = "",
		env_mask_char = "",
	},
	ft = {
		octo = "",
	},
	dap = {
		Stopped = { "󰁕 ", "DiagnosticWarn", "DapStoppedLine" },
		Breakpoint = " ",
		BreakpointCondition = " ",
		BreakpointRejected = { " ", "DiagnosticError" },
		LogPoint = ".>",
	},
	diagnostics = {
		Error = " ",
		Warn = " ",
		Hint = " ",
		Info = " ",
	},
	mason = {
		package_installed = " ",
		package_pending = " ",
		package_uninstalled = " ",
	},
	git = {
		added = " ",
		modified = " ",
		removed = " ",
	},
	blink_cmp_git = {
		Mention = "",
		openPR = "",
		openedPR = "",
		closedPR = "",
		mergedPR = "",
		draftPR = "",
		lockedPR = "",
		openIssue = "",
		openedIssue = "",
		reopenedIssue = "",
		completedIssue = "",
		closedIssue = "",
		not_plannedIssue = "",
		duplicateIssue = "",
		lockedIssue = "",
	},
	kinds = {
		Emoji = "󰞅",
		Ripgrep = "󱎸",
		Array = " ",
		Boolean = "󰨙 ",
		Class = " ",
		Codeium = "󰘦 ",
		Color = " ",
		Control = " ",
		Collapsed = " ",
		Constant = "󰏿 ",
		Constructor = " ",
		Copilot = " ",
		Enum = " ",
		EnumMember = " ",
		Event = " ",
		Field = " ",
		File = " ",
		Folder = " ",
		Function = "󰊕 ",
		Interface = " ",
		Key = " ",
		Keyword = " ",
		Method = "󰊕 ",
		Module = " ",
		Namespace = "󰦮 ",
		Null = " ",
		Number = "󰎠 ",
		Object = " ",
		Operator = " ",
		Package = " ",
		Property = " ",
		Reference = " ",
		Snippet = "󱄽 ",
		String = " ",
		Struct = "󰆼 ",
		Supermaven = " ",
		TabNine = "󰏚 ",
		Text = " ",
		TypeParameter = " ",
		Unit = " ",
		Value = " ",
		Variable = "󰀫 ",
	},
}

return M
