return {
	"catgoose/nvim-colorizer.lua",
	event = "BufReadPre",
	opts = {
		filetypes = {
			"*",
			"!Trouble",
			"!alpha",
			"!dashboard",
			"!fzf",
			"!help",
			"!lazy",
			"!mason",
			"!neo-tree",
			"!notify",
			"!snacks_dashboard",
			"!snacks_notif",
			"!snacks_terminal",
			"!snacks_win",
			"!toggleterm",
			"!trouble",
		},
		user_default_options = {
			virtualtext = require("configs.icons").misc.color_text,
			mode = "virtualtext",
			RRGGBBAA = true,
			AARRGGBB = true,
			css = true,
			css_fn = true,
			virtualtext_inline = "before",
			tailwind = true,
			tailwind_opts = {
				update_names = true,
			},
			sass = { enable = true, parsers = { "css" } },
		},
	},
}
