name: Build NixOS

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Free disk space for Nix 💽
        uses: wimpysworld/nothing-but-nix@687c797a730352432950c707ab493fcc951818d7 # v10
        with:
          hatchet-protocol: cleave

      - name: Install Nix ❄️
        uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Build NixOS system 🏗️
        run: |
          nix run github:Mic92/nix-fast-build -- \
            --skip-cached \
            --cachix-cache muntasirszn \
            --flake "./nixos/.config/nixos#nixosConfigurations.nixos.config.system.build.toplevel"
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
